import type {
  Assignment,
  Campus,
  FetActivity,
  FetBuildResult,
  SchoolClass,
  Teacher,
  TeacherWorkloadLimit,
  TimeSlot,
  TimetableProject
} from "./types";
import { buildCalendar, isValidSlot } from "./timeSlots";
import { parseSplitPattern, validateSplitPattern } from "./splitPattern";

const FET_VERSION = "7.9.4";

type NormalizedTeacherWorkloadLimit = {
  maxRealDays?: number;
  minRealDays?: number;
  maxSessions?: number;
  minSessions?: number;
  maxMornings?: number;
  maxAfternoons?: number;
  minMornings?: number;
  minAfternoons?: number;
};

export function buildFetFile(project: TimetableProject): FetBuildResult {
  const calendar = buildCalendar(project.settings);
  const warnings: string[] = [];
  const errors: string[] = [];
  const campuses = getCampuses(project);
  if (campuses.length === 0) errors.push("Cần khai báo ít nhất một điểm trường.");

  if (!project.settings.institutionName.trim()) errors.push("Tên trường không được để trống.");
  if (project.settings.numberOfDays < 1 || project.settings.numberOfDays > 7) {
    errors.push("Số ngày phải nằm trong khoảng 1..7.");
  }
  if (project.settings.periodsPerSession < 1 || project.settings.periodsPerSession > 12) {
    errors.push("Số tiết tối đa mỗi buổi phải nằm trong khoảng 1..12.");
  }

  const cleanAssignments = project.assignments.filter((assignment) => assignment.campusName && assignment.className && assignment.subjectName);
  for (const assignment of cleanAssignments) {
    if (!Number.isInteger(assignment.weeklyPeriods) || assignment.weeklyPeriods <= 0) {
      errors.push(`${assignment.className} - ${assignment.subjectName}: tổng tiết phải là số nguyên dương.`);
    }
    errors.push(...validateSplitPattern(assignment.splitPattern, assignment.weeklyPeriods, project.settings.periodsPerSession)
      .map((message) => `${assignment.className} - ${assignment.subjectName}: ${message}`));
  }

  const activities = buildActivities(cleanAssignments, errors);
  const assignmentActivityIds = activities.reduce<Record<string, number[]>>((acc, activity) => {
    acc[activity.assignmentId] ??= [];
    acc[activity.assignmentId].push(activity.id);
    return acc;
  }, {});

  warnCapacity(project, cleanAssignments, calendar.dayNames.length * calendar.hourNames.length, warnings);

  const subjects = uniqueNames([
    ...project.subjects.map((subject) => subject.name),
    ...cleanAssignments.map((assignment) => assignment.subjectName)
  ]);
  const tags = uniqueNames(cleanAssignments.map((assignment) => assignment.tag || ""));
  const teachers = mergeTeachers(project.teachers, cleanAssignments);
  const classes = uniqueClasses(project, cleanAssignments);

  const timeConstraintXml = buildTimeConstraints(project, activities, assignmentActivityIds, errors, warnings);
  const xml = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<fet version="${FET_VERSION}">`,
    `  <Mode>${calendar.modeName}</Mode>`,
    node("Institution_Name", project.settings.institutionName, 2),
    node("Comments", "Generated by TKB Tiểu Học; constraints are serialized to official FET XML tags.", 2),
    buildDaysXml(calendar.dayNames),
    calendar.modeName === "Mornings_Afternoons" ? buildRealDaysXml(calendar.realDayNames) : "",
    buildHoursXml(calendar.hourNames),
    calendar.modeName === "Mornings_Afternoons" ? buildRealHoursXml(calendar.realHourNames) : "",
    buildSubjectsXml(subjects),
    buildTagsXml(tags),
    buildTeachersXml(teachers, calendar.modeName === "Mornings_Afternoons"),
    buildStudentsXml(project, classes),
    buildActivitiesXml(project, activities),
    buildBuildingsXml(campuses),
    buildRoomsXml(project, classes),
    timeConstraintXml,
    buildSpaceConstraintsXml(project, classes, warnings),
    `</fet>`
  ].filter(Boolean).join("\n");

  return { xml: `${xml}\n`, calendar, activities, assignmentActivityIds, warnings, errors };
}

function buildActivities(assignments: Assignment[], errors: string[]): FetActivity[] {
  const activities: FetActivity[] = [];
  let nextId = 1;

  for (const assignment of assignments) {
    let parts: number[] = [];
    try {
      parts = parseSplitPattern(assignment.splitPattern);
    } catch {
      continue;
    }

    const groupId = parts.length > 1 ? nextId : 0;
    parts.forEach((duration, splitIndex) => {
      if (!Number.isInteger(duration) || duration <= 0) {
        errors.push(`${assignment.className} - ${assignment.subjectName}: duration không hợp lệ.`);
        return;
      }

      activities.push({
        id: nextId,
        assignmentId: assignment.id,
        campusName: assignment.campusName,
        className: assignment.className,
        subjectName: assignment.subjectName,
        teacherName: assignment.teacherName,
        tag: assignment.tag || "",
        duration,
        totalDuration: assignment.weeklyPeriods,
        groupId,
        splitIndex
      });
      nextId += 1;
    });
  }

  return activities;
}

function buildTimeConstraints(
  project: TimetableProject,
  activities: FetActivity[],
  assignmentActivityIds: Record<string, number[]>,
  errors: string[],
  warnings: string[]
): string {
  const calendar = buildCalendar(project.settings);
  const lines: string[] = [];
  lines.push(`  <Time_Constraints_List>`);
  lines.push(`    <ConstraintBasicCompulsoryTime>`);
  lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
  lines.push(`      <Active>true</Active>`);
  lines.push(`      <Comments></Comments>`);
  lines.push(`    </ConstraintBasicCompulsoryTime>`);

  const teacherUnavailable = project.constraints.teacherUnavailableTimes
    .filter((item) => item.teacherName.trim() && item.slots.length > 0);

  for (const item of teacherUnavailable) {
    const validSlots = item.slots.filter((slot) => isValidSlot(calendar, slot));
    if (validSlots.length !== item.slots.length) {
      warnings.push(`${item.teacherName}: bỏ qua một số ô bận không còn nằm trong khung thời gian hiện tại.`);
    }
    if (validSlots.length === 0) continue;
    lines.push(`    <ConstraintTeacherNotAvailableTimes>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(node("Teacher", item.teacherName, 6));
    lines.push(`      <Number_of_Not_Available_Times>${validSlots.length}</Number_of_Not_Available_Times>`);
    for (const slot of validSlots) {
      lines.push(`      <Not_Available_Time>`);
      lines.push(node("Day", slot.dayLabel, 8));
      lines.push(node("Hour", hourName(project, slot.periodIndex), 8));
      lines.push(`      </Not_Available_Time>`);
    }
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments></Comments>`);
    lines.push(`    </ConstraintTeacherNotAvailableTimes>`);
  }

  if (project.constraints.basic.teacherMaxGapsPerDayEnabled) {
    lines.push(`    <ConstraintTeachersMaxGapsPerDay>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(`      <Max_Gaps>${clampInteger(project.constraints.basic.teacherMaxGapsPerDay, 0, 100)}</Max_Gaps>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments>Primary-school compact-session rule. Max gaps per FET day = per half-day in Mornings_Afternoons mode.</Comments>`);
    lines.push(`    </ConstraintTeachersMaxGapsPerDay>`);
  }

  if (project.constraints.basic.studentsMaxGapsPerDayEnabled) {
    lines.push(`    <ConstraintStudentsMaxGapsPerDay>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(`      <Max_Gaps>${clampInteger(project.constraints.basic.studentsMaxGapsPerDay, 0, 100)}</Max_Gaps>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments></Comments>`);
    lines.push(`    </ConstraintStudentsMaxGapsPerDay>`);
  }

  if (project.constraints.basic.homeroomTeachersAllRealDaysEnabled) {
    const homeroomTeachers = uniqueNames(project.classes.map((schoolClass) => schoolClass.homeroomTeacherName || ""));
    if (homeroomTeachers.length === 0) {
      warnings.push("Chưa có giáo viên chủ nhiệm nào được khai báo, nên không sinh ràng buộc GVCN đi đủ ngày.");
    }

    for (const teacherName of homeroomTeachers) {
      const activityCount = activities.filter((activity) => activity.teacherName === teacherName).length;
      if (activityCount < project.settings.numberOfDays) {
        errors.push(`${teacherName}: chỉ có ${activityCount} hoạt động có thể xếp, không đủ để đi ${project.settings.numberOfDays} ngày thật.`);
      }

      const fullyBusyDays = realDaysFullyUnavailable(project, teacherName);
      if (fullyBusyDays.length > 0) {
        errors.push(`${teacherName}: bị đánh bận toàn bộ ngày ${fullyBusyDays.join(", ")}, mâu thuẫn với ràng buộc GVCN đi đủ ngày.`);
      }

      if (project.settings.mode === "full-day") {
        lines.push(`    <ConstraintTeacherMinRealDaysPerWeek>`);
      } else {
        lines.push(`    <ConstraintTeacherMinDaysPerWeek>`);
      }
      lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
      lines.push(node("Teacher", teacherName, 6));
      lines.push(`      <Minimum_Days_Per_Week>${project.settings.numberOfDays}</Minimum_Days_Per_Week>`);
      lines.push(`      <Active>true</Active>`);
      lines.push(`      <Comments>Homeroom teacher must be present every real school day.</Comments>`);
      lines.push(project.settings.mode === "full-day"
        ? `    </ConstraintTeacherMinRealDaysPerWeek>`
        : `    </ConstraintTeacherMinDaysPerWeek>`);
    }
  }

  if (project.constraints.basic.teacherMinHoursDailyEnabled) {
    const minimumHours = clampInteger(project.constraints.basic.teacherMinHoursDaily, 1, 100);
    if (minimumHours > project.settings.periodsPerSession) {
      errors.push(`Tối thiểu ${minimumHours} tiết mỗi buổi vượt số tiết tối đa mỗi buổi (${project.settings.periodsPerSession}).`);
    }

    const teacherTotals = totalPeriodsByTeacher(project.assignments);
    const activeTeachers = uniqueNames(project.assignments.map((assignment) => assignment.teacherName));
    const lowTotalTeachers = activeTeachers.filter((teacherName) => (teacherTotals.get(teacherName) || 0) > 0 && (teacherTotals.get(teacherName) || 0) < minimumHours);
    const constrainedTeachers = project.constraints.basic.teacherMinHoursDailySkipLowTotalTeachers
      ? activeTeachers.filter((teacherName) => (teacherTotals.get(teacherName) || 0) >= minimumHours)
      : activeTeachers;

    if (!project.constraints.basic.teacherMinHoursDailySkipLowTotalTeachers && lowTotalTeachers.length > 0) {
      errors.push(`${lowTotalTeachers.join(", ")} có tổng tiết/tuần nhỏ hơn ${minimumHours}, nên ràng buộc GV dạy tối thiểu mỗi buổi sẽ vô nghiệm.`);
    }

    if (project.constraints.basic.teacherMinHoursDailySkipLowTotalTeachers && lowTotalTeachers.length > 0) {
      warnings.push(`Bỏ qua ràng buộc tối thiểu ${minimumHours} tiết/buổi cho ${lowTotalTeachers.join(", ")} vì tổng tiết/tuần nhỏ hơn mức tối thiểu.`);
    }

    for (const teacherName of constrainedTeachers) {
      lines.push(`    <ConstraintTeacherMinHoursDaily>`);
      lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
      lines.push(node("Teacher", teacherName, 6));
      lines.push(`      <Minimum_Hours_Daily>${minimumHours}</Minimum_Hours_Daily>`);
      lines.push(`      <Allow_Empty_Days>true</Allow_Empty_Days>`);
      lines.push(`      <Active>true</Active>`);
      lines.push(`      <Comments>If a teacher works in a session, the session must contain at least this many periods.</Comments>`);
      lines.push(`    </ConstraintTeacherMinHoursDaily>`);
    }
  }

  if (project.constraints.basic.mainSubjectAfterFlagCeremonyEnabled) {
    lines.push(...buildMainSubjectAfterFlagCeremonyConstraints(project, activities, calendar, errors, warnings));
  }

  lines.push(...buildTeacherWorkloadLimitConstraints(project, errors));

  for (const assignment of project.assignments) {
    const ids = assignmentActivityIds[assignment.id] || [];
    if (ids.length <= 1 || assignment.minDays <= 0) continue;

    lines.push(`    <ConstraintMinDaysBetweenActivities>`);
    lines.push(`      <Weight_Percentage>${weightPercent(assignment.weight)}</Weight_Percentage>`);
    lines.push(`      <Consecutive_If_Same_Day>${assignment.consecutiveIfSameDay ? "true" : "false"}</Consecutive_If_Same_Day>`);
    lines.push(`      <Number_of_Activities>${ids.length}</Number_of_Activities>`);
    ids.forEach((id) => lines.push(`      <Activity_Id>${id}</Activity_Id>`));
    lines.push(`      <MinDays>${clampInteger(assignment.minDays, 0, 100)}</MinDays>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments></Comments>`);
    lines.push(`    </ConstraintMinDaysBetweenActivities>`);
  }

  for (const preferred of project.constraints.preferredTimes) {
    const slot = { dayLabel: preferred.dayLabel, periodIndex: preferred.periodIndex };
    if (!isValidSlot(buildCalendar(project.settings), slot)) {
      errors.push(`Ràng buộc ưu tiên ${preferred.id}: thời gian không hợp lệ.`);
      continue;
    }

    const matchingActivities = activities.filter((activity) => matchesPreferred(activity, preferred));
    const selectedActivities = firstSplitFromEachAssignment(matchingActivities);

    if (selectedActivities.length === 0) {
      warnings.push(`Ràng buộc ưu tiên ${preferred.id}: không tìm thấy hoạt động phù hợp.`);
      continue;
    }

    for (const activity of selectedActivities) {
      lines.push(`    <ConstraintActivityPreferredStartingTime>`);
      lines.push(`      <Weight_Percentage>${weightPercent(preferred.weight)}</Weight_Percentage>`);
      lines.push(`      <Activity_Id>${activity.id}</Activity_Id>`);
      lines.push(node("Day", preferred.dayLabel, 6));
      lines.push(node("Hour", hourName(project, preferred.periodIndex), 6));
      lines.push(`      <Permanently_Locked>${preferred.permanentlyLocked ? "true" : "false"}</Permanently_Locked>`);
      lines.push(`      <Active>true</Active>`);
      lines.push(`      <Comments></Comments>`);
      lines.push(`    </ConstraintActivityPreferredStartingTime>`);
    }
  }

  for (const group of project.constraints.sameTimeGroups) {
    const ids = group.assignmentIds
      .flatMap((assignmentId) => assignmentActivityIds[assignmentId]?.slice(0, 1) || [])
      .filter((id, index, arr) => arr.indexOf(id) === index);

    if (ids.length < 2) {
      warnings.push(`Ràng buộc cùng thời điểm "${group.name}" cần ít nhất 2 hoạt động.`);
      continue;
    }

    lines.push(`    <ConstraintActivitiesSameStartingTime>`);
    lines.push(`      <Weight_Percentage>${weightPercent(group.weight)}</Weight_Percentage>`);
    lines.push(`      <Number_of_Activities>${ids.length}</Number_of_Activities>`);
    ids.forEach((id) => lines.push(`      <Activity_Id>${id}</Activity_Id>`));
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments></Comments>`);
    lines.push(`    </ConstraintActivitiesSameStartingTime>`);
  }

  lines.push(`  </Time_Constraints_List>`);
  return lines.join("\n");
}

function buildTeacherWorkloadLimitConstraints(project: TimetableProject, errors: string[]): string[] {
  const lines: string[] = [];
  const calendar = buildCalendar(project.settings);
  const maxRealDays = project.settings.numberOfDays;
  const maxSessions = calendar.dayNames.length;
  const limits = mergeTeacherWorkloadLimits(project.constraints.teacherWorkloadLimits || []);

  for (const limit of limits) {
    const teacherName = limit.teacherName.trim();
    if (!teacherName) continue;

    const values = normalizeTeacherWorkloadLimit(limit);
    validateTeacherWorkloadLimit(teacherName, values, maxRealDays, maxSessions, errors);

    const weight = weightPercent(limit.weight);
    const realMaxTag = project.settings.mode === "full-day" ? "ConstraintTeacherMaxRealDaysPerWeek" : "ConstraintTeacherMaxDaysPerWeek";
    const realMinTag = project.settings.mode === "full-day" ? "ConstraintTeacherMinRealDaysPerWeek" : "ConstraintTeacherMinDaysPerWeek";

    if (values.maxRealDays !== undefined) {
      pushTeacherDaysConstraint(lines, realMaxTag, teacherName, "Max_Days_Per_Week", values.maxRealDays, weight, "Teacher maximum real school days per week.");
    }
    if (values.minRealDays !== undefined) {
      pushTeacherDaysConstraint(lines, realMinTag, teacherName, "Minimum_Days_Per_Week", values.minRealDays, weight, "Teacher minimum real school days per week.");
    }
    if (values.maxSessions !== undefined) {
      pushTeacherDaysConstraint(lines, "ConstraintTeacherMaxDaysPerWeek", teacherName, "Max_Days_Per_Week", values.maxSessions, weight, "Teacher maximum sessions per week. In this app each morning/afternoon session is a FET day.");
    }
    if (values.minSessions !== undefined) {
      pushTeacherDaysConstraint(lines, "ConstraintTeacherMinDaysPerWeek", teacherName, "Minimum_Days_Per_Week", values.minSessions, weight, "Teacher minimum sessions per week. In this app each morning/afternoon session is a FET day.");
    }
    if (values.maxMornings !== undefined) {
      pushTeacherDaysConstraint(lines, "ConstraintTeacherMaxMorningsPerWeek", teacherName, "Max_Mornings_Per_Week", values.maxMornings, weight, "Teacher maximum mornings per week.");
    }
    if (values.maxAfternoons !== undefined) {
      pushTeacherDaysConstraint(lines, "ConstraintTeacherMaxAfternoonsPerWeek", teacherName, "Max_Afternoons_Per_Week", values.maxAfternoons, weight, "Teacher maximum afternoons per week.");
    }
    if (values.minMornings !== undefined) {
      pushTeacherDaysConstraint(lines, "ConstraintTeacherMinMorningsPerWeek", teacherName, "Minimum_Mornings_Per_Week", values.minMornings, weight, "Teacher minimum mornings per week.");
    }
    if (values.minAfternoons !== undefined) {
      pushTeacherDaysConstraint(lines, "ConstraintTeacherMinAfternoonsPerWeek", teacherName, "Minimum_Afternoons_Per_Week", values.minAfternoons, weight, "Teacher minimum afternoons per week.");
    }
  }

  return lines;
}

function normalizeTeacherWorkloadLimit(limit: TeacherWorkloadLimit): NormalizedTeacherWorkloadLimit {
  return {
    maxRealDays: normalizeOptionalInteger(limit.maxRealDays),
    minRealDays: normalizeOptionalInteger(limit.minRealDays),
    maxSessions: normalizeOptionalInteger(limit.maxSessions),
    minSessions: normalizeOptionalInteger(limit.minSessions),
    maxMornings: normalizeOptionalInteger(limit.maxMornings),
    maxAfternoons: normalizeOptionalInteger(limit.maxAfternoons),
    minMornings: normalizeOptionalInteger(limit.minMornings),
    minAfternoons: normalizeOptionalInteger(limit.minAfternoons)
  };
}

function validateTeacherWorkloadLimit(
  teacherName: string,
  values: NormalizedTeacherWorkloadLimit,
  maxRealDays: number,
  maxSessions: number,
  errors: string[]
) {
  validateOptionalLimit(`${teacherName}: số ngày max`, values.maxRealDays, 0, maxRealDays, errors);
  validateOptionalLimit(`${teacherName}: số ngày min`, values.minRealDays, 0, maxRealDays, errors);
  validateOptionalLimit(`${teacherName}: số buổi max`, values.maxSessions, 0, maxSessions, errors);
  validateOptionalLimit(`${teacherName}: số buổi min`, values.minSessions, 0, maxSessions, errors);
  validateOptionalLimit(`${teacherName}: số buổi sáng max`, values.maxMornings, 0, maxRealDays, errors);
  validateOptionalLimit(`${teacherName}: số buổi chiều max`, values.maxAfternoons, 0, maxRealDays, errors);
  validateOptionalLimit(`${teacherName}: số buổi sáng min`, values.minMornings, 0, maxRealDays, errors);
  validateOptionalLimit(`${teacherName}: số buổi chiều min`, values.minAfternoons, 0, maxRealDays, errors);

  if (values.maxRealDays !== undefined && values.minRealDays !== undefined && values.minRealDays > values.maxRealDays) {
    errors.push(`${teacherName}: số ngày min không được lớn hơn số ngày max.`);
  }
  if (values.maxSessions !== undefined && values.minSessions !== undefined && values.minSessions > values.maxSessions) {
    errors.push(`${teacherName}: số buổi min không được lớn hơn số buổi max.`);
  }
  if (values.maxMornings !== undefined && values.minMornings !== undefined && values.minMornings > values.maxMornings) {
    errors.push(`${teacherName}: số buổi sáng min không được lớn hơn số buổi sáng max.`);
  }
  if (values.maxAfternoons !== undefined && values.minAfternoons !== undefined && values.minAfternoons > values.maxAfternoons) {
    errors.push(`${teacherName}: số buổi chiều min không được lớn hơn số buổi chiều max.`);
  }
}

function validateOptionalLimit(label: string, value: number | undefined, min: number, max: number, errors: string[]) {
  if (value === undefined) return;
  if (value < min || value > max) {
    errors.push(`${label} phải nằm trong khoảng ${min}..${max}.`);
  }
}

function pushTeacherDaysConstraint(
  lines: string[],
  constraintName: string,
  teacherName: string,
  valueTag:
    | "Max_Days_Per_Week"
    | "Minimum_Days_Per_Week"
    | "Max_Mornings_Per_Week"
    | "Max_Afternoons_Per_Week"
    | "Minimum_Mornings_Per_Week"
    | "Minimum_Afternoons_Per_Week",
  value: number,
  weight: string,
  comments: string
) {
  lines.push(`    <${constraintName}>`);
  lines.push(`      <Weight_Percentage>${weight}</Weight_Percentage>`);
  lines.push(node("Teacher", teacherName, 6));
  lines.push(`      <${valueTag}>${value}</${valueTag}>`);
  lines.push(`      <Active>true</Active>`);
  lines.push(node("Comments", comments, 6));
  lines.push(`    </${constraintName}>`);
}

function mergeTeacherWorkloadLimits(limits: TeacherWorkloadLimit[]): TeacherWorkloadLimit[] {
  const byTeacher = new Map<string, TeacherWorkloadLimit>();

  for (const limit of limits) {
    const teacherName = limit.teacherName?.trim();
    if (!teacherName) continue;

    const normalized: TeacherWorkloadLimit = {
      teacherName,
      maxRealDays: limit.maxRealDays,
      minRealDays: limit.minRealDays,
      maxSessions: limit.maxSessions,
      minSessions: limit.minSessions,
      maxMornings: limit.maxMornings,
      maxAfternoons: limit.maxAfternoons,
      minMornings: limit.minMornings,
      minAfternoons: limit.minAfternoons,
      weight: Number.isFinite(limit.weight) ? limit.weight : 1
    };
    const current = byTeacher.get(teacherName);
    if (!current) {
      byTeacher.set(teacherName, normalized);
      continue;
    }

    current.maxRealDays = mergeOptionalMin(current.maxRealDays, normalized.maxRealDays);
    current.minRealDays = mergeOptionalMax(current.minRealDays, normalized.minRealDays);
    current.maxSessions = mergeOptionalMin(current.maxSessions, normalized.maxSessions);
    current.minSessions = mergeOptionalMax(current.minSessions, normalized.minSessions);
    current.maxMornings = mergeOptionalMin(current.maxMornings, normalized.maxMornings);
    current.maxAfternoons = mergeOptionalMin(current.maxAfternoons, normalized.maxAfternoons);
    current.minMornings = mergeOptionalMax(current.minMornings, normalized.minMornings);
    current.minAfternoons = mergeOptionalMax(current.minAfternoons, normalized.minAfternoons);
    current.weight = Number.isFinite(current.weight) ? current.weight : normalized.weight;
  }

  return Array.from(byTeacher.values());
}

function mergeOptionalMin(a: number | undefined, b: number | undefined): number | undefined {
  if (a === undefined) return b;
  if (b === undefined) return a;
  return Math.min(a, b);
}

function mergeOptionalMax(a: number | undefined, b: number | undefined): number | undefined {
  if (a === undefined) return b;
  if (b === undefined) return a;
  return Math.max(a, b);
}

function buildMainSubjectAfterFlagCeremonyConstraints(
  project: TimetableProject,
  activities: FetActivity[],
  calendar: ReturnType<typeof buildCalendar>,
  errors: string[],
  warnings: string[]
): string[] {
  const lines: string[] = [];
  const nextSlots = findSlotsAfterFlagCeremony(project, activities, calendar, errors, warnings);
  if (nextSlots.length === 0) return lines;

  const assignmentsById = new Map(project.assignments.map((assignment) => [assignment.id, assignment]));
  const classRefs = uniqueClasses(project, project.assignments);

  for (const schoolClass of classRefs) {
    const className = `${schoolClass.campusName} - ${schoolClass.name}`;
    const mainSubjectActivityIds = activities
      .filter((activity) => activity.campusName === schoolClass.campusName && activity.className === schoolClass.name && assignmentsById.get(activity.assignmentId)?.isMainSubject)
      .map((activity) => activity.id);

    if (mainSubjectActivityIds.length === 0) {
      errors.push(`${className}: chưa có môn chính nào trong PCCM, nên không thể áp dụng ràng buộc sau tiết Chào cờ.`);
      continue;
    }

    const classSlots = nextSlots.filter((item) => item.classKeys.includes(classKey(schoolClass.campusName, schoolClass.name)));
    for (const item of classSlots) {
      lines.push(`    <ConstraintActivitiesOccupyMinTimeSlotsFromSelection>`);
      lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
      lines.push(`      <Number_of_Activities>${mainSubjectActivityIds.length}</Number_of_Activities>`);
      mainSubjectActivityIds.forEach((id) => lines.push(`      <Activity_Id>${id}</Activity_Id>`));
      lines.push(`      <Number_of_Selected_Time_Slots>1</Number_of_Selected_Time_Slots>`);
      lines.push(`      <Selected_Time_Slot>`);
      lines.push(node("Day", item.slot.dayLabel, 8));
      lines.push(node("Hour", hourName(project, item.slot.periodIndex), 8));
      lines.push(`      </Selected_Time_Slot>`);
      lines.push(`      <Min_Number_of_Occupied_Time_Slots>1</Min_Number_of_Occupied_Time_Slots>`);
      lines.push(`      <Active>true</Active>`);
      lines.push(`      <Comments>After flag ceremony, this class must study a main subject.</Comments>`);
      lines.push(`    </ConstraintActivitiesOccupyMinTimeSlotsFromSelection>`);
    }
  }

  return lines;
}

function findSlotsAfterFlagCeremony(
  project: TimetableProject,
  activities: FetActivity[],
  calendar: ReturnType<typeof buildCalendar>,
  errors: string[],
  warnings: string[]
): Array<{ slot: TimeSlot; classKeys: string[] }> {
  const classRefs = uniqueClasses(project, project.assignments);
  const allClassKeys = classRefs.map((schoolClass) => classKey(schoolClass.campusName, schoolClass.name));
  const slots = new Map<string, { slot: TimeSlot; classKeys: string[] }>();

  for (const preferred of project.constraints.preferredTimes) {
    const slot = { dayLabel: preferred.dayLabel, periodIndex: preferred.periodIndex };
    if (!isValidSlot(calendar, slot)) continue;

    const matchingFlagActivities = activities.filter((activity) => (
      isFlagCeremonySubject(activity.subjectName) && matchesPreferred(activity, preferred)
    ));
    if (matchingFlagActivities.length === 0) continue;

    if (preferred.weight < 1 || !preferred.permanentlyLocked) {
      warnings.push("Ràng buộc sau tiết Chào cờ nên đi cùng một RB thời gian ưu tiên Chào cờ có Trọng số = 1 và Khóa cứng.");
    }

    const duration = Math.max(1, ...matchingFlagActivities.map((activity) => activity.duration));
    const nextPeriodIndex = preferred.periodIndex + duration;
    if (nextPeriodIndex >= calendar.hourNames.length) {
      errors.push(`Không thể áp dụng ràng buộc sau tiết Chào cờ vì ${preferred.dayLabel} ${hourName(project, preferred.periodIndex)} là tiết cuối hoặc Chào cờ kéo dài đến cuối buổi.`);
      continue;
    }

    const affectedClasses = preferred.className
      ? classRefs
        .filter((schoolClass) => (!preferred.campusName || schoolClass.campusName === preferred.campusName) && schoolClass.name === preferred.className)
        .map((schoolClass) => classKey(schoolClass.campusName, schoolClass.name))
      : (preferred.campusName
        ? classRefs.filter((schoolClass) => schoolClass.campusName === preferred.campusName).map((schoolClass) => classKey(schoolClass.campusName, schoolClass.name))
        : allClassKeys);
    const key = `${preferred.dayLabel}::${nextPeriodIndex}`;
    const existing = slots.get(key);
    if (existing) {
      existing.classKeys = uniqueNames([...existing.classKeys, ...affectedClasses]);
    } else {
      slots.set(key, {
        slot: { dayLabel: preferred.dayLabel, periodIndex: nextPeriodIndex },
        classKeys: affectedClasses
      });
    }
  }

  if (slots.size === 0) {
    errors.push("Đã bật ràng buộc sau tiết Chào cờ, nhưng chưa có RB thời gian ưu tiên cho môn Chào cờ.");
  }

  return Array.from(slots.values());
}

function matchesPreferred(activity: FetActivity, preferred: { campusName?: string; subjectName: string; className: string; teacherName: string; tag: string }): boolean {
  return (!preferred.campusName || activity.campusName === preferred.campusName)
    && (!preferred.subjectName || activity.subjectName === preferred.subjectName)
    && (!preferred.className || activity.className === preferred.className)
    && (!preferred.teacherName || activity.teacherName === preferred.teacherName)
    && (!preferred.tag || activity.tag === preferred.tag);
}

function firstSplitFromEachAssignment(activities: FetActivity[]): FetActivity[] {
  const byAssignment = new Map<string, FetActivity>();
  for (const activity of activities) {
    const current = byAssignment.get(activity.assignmentId);
    if (!current || activity.splitIndex < current.splitIndex) {
      byAssignment.set(activity.assignmentId, activity);
    }
  }
  return Array.from(byAssignment.values());
}

function buildBuildingsXml(campuses: Campus[]): string {
  return [
    `  <Buildings_List>`,
    ...campuses.map((campus) => [
      `    <Building>`,
      node("Name", campus.name, 6),
      `      <Long_Name></Long_Name>`,
      `      <Code></Code>`,
      `      <Comments>Điểm trường</Comments>`,
      `    </Building>`
    ].join("\n")),
    `  </Buildings_List>`
  ].join("\n");
}

function buildRoomsXml(project: TimetableProject, classes: SchoolClass[]): string {
  return [
    `  <Rooms_List>`,
    ...classes.map((schoolClass) => [
      `    <Room>`,
      node("Name", roomNameForClass(project, schoolClass), 6),
      `      <Long_Name></Long_Name>`,
      `      <Code></Code>`,
      node("Building", schoolClass.campusName, 6),
      `      <Capacity>${schoolClass.studentCount || 0}</Capacity>`,
      `      <Virtual>false</Virtual>`,
      `      <Comments>Phòng giả để gắn lớp với điểm trường.</Comments>`,
      `    </Room>`
    ].join("\n")),
    `  </Rooms_List>`
  ].join("\n");
}

function buildSpaceConstraintsXml(project: TimetableProject, classes: SchoolClass[], warnings: string[]): string {
  const lines = [
    `  <Space_Constraints_List>`,
    `    <ConstraintBasicCompulsorySpace>`,
    `      <Weight_Percentage>100</Weight_Percentage>`,
    `      <Active>true</Active>`,
    `      <Comments></Comments>`,
    `    </ConstraintBasicCompulsorySpace>`
  ];

  for (const schoolClass of classes) {
    lines.push(`    <ConstraintStudentsSetHomeRoom>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(node("Students", fetClassName(project, schoolClass), 6));
    lines.push(node("Room", roomNameForClass(project, schoolClass), 6));
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments>Gắn lớp với điểm trường để FET xử lý di chuyển giáo viên.</Comments>`);
    lines.push(`    </ConstraintStudentsSetHomeRoom>`);
  }

  const hasMultipleCampuses = getCampuses(project).length > 1;
  if (!hasMultipleCampuses) {
    lines.push(`  </Space_Constraints_List>`);
    return lines.join("\n");
  }

  if (project.constraints.basic.teacherMaxCampusChangesPerSessionEnabled) {
    lines.push(`    <ConstraintTeachersMaxBuildingChangesPerDay>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(`      <Max_Building_Changes_Per_Day>${clampInteger(project.constraints.basic.teacherMaxCampusChangesPerSession, 0, 100)}</Max_Building_Changes_Per_Day>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments>Giới hạn số lần giáo viên đổi điểm trường trong một buổi FET.</Comments>`);
    lines.push(`    </ConstraintTeachersMaxBuildingChangesPerDay>`);
  }

  if (project.constraints.basic.teacherMinGapsBetweenCampusChangesEnabled) {
    lines.push(`    <ConstraintTeachersMinGapsBetweenBuildingChanges>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(`      <Min_Gaps_Between_Building_Changes>${clampInteger(project.constraints.basic.teacherMinGapsBetweenCampusChanges, 0, 100)}</Min_Gaps_Between_Building_Changes>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments>Số tiết trống tối thiểu khi giáo viên đổi điểm trường.</Comments>`);
    lines.push(`    </ConstraintTeachersMinGapsBetweenBuildingChanges>`);
  }

  if (project.constraints.basic.teacherMaxCampusChangesPerRealDayEnabled) {
    if (project.settings.mode !== "full-day") {
      warnings.push("Ràng buộc đổi điểm trường theo ngày thật chỉ có ý nghĩa đầy đủ khi dùng kiểu thời khóa biểu sáng/chiều.");
    }
    lines.push(`    <ConstraintTeachersMaxBuildingChangesPerRealDay>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(`      <Max_Building_Changes_Per_Day>${clampInteger(project.constraints.basic.teacherMaxCampusChangesPerRealDay, 0, 100)}</Max_Building_Changes_Per_Day>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments>Giới hạn số lần giáo viên đổi điểm trường trong một ngày thật.</Comments>`);
    lines.push(`    </ConstraintTeachersMaxBuildingChangesPerRealDay>`);
  }

  if (project.constraints.basic.teacherMaxCampusChangesPerWeekEnabled) {
    lines.push(`    <ConstraintTeachersMaxBuildingChangesPerWeek>`);
    lines.push(`      <Weight_Percentage>100</Weight_Percentage>`);
    lines.push(`      <Max_Building_Changes_Per_Week>${clampInteger(project.constraints.basic.teacherMaxCampusChangesPerWeek, 0, 100)}</Max_Building_Changes_Per_Week>`);
    lines.push(`      <Active>true</Active>`);
    lines.push(`      <Comments>Giới hạn số lần giáo viên đổi điểm trường trong một tuần.</Comments>`);
    lines.push(`    </ConstraintTeachersMaxBuildingChangesPerWeek>`);
  }

  lines.push(`  </Space_Constraints_List>`);
  return lines.join("\n");
}

function buildDaysXml(days: string[]): string {
  return [
    `  <Days_List>`,
    `    <Number_of_Days>${days.length}</Number_of_Days>`,
    ...days.map((day) => [
      `    <Day>`,
      node("Name", day, 6),
      `      <Long_Name></Long_Name>`,
      `    </Day>`
    ].join("\n")),
    `  </Days_List>`
  ].join("\n");
}

function buildRealDaysXml(days: string[]): string {
  return [
    `  <Real_Days_List>`,
    `    <Number_of_Real_Days>${days.length}</Number_of_Real_Days>`,
    ...days.map((day) => [
      `    <Real_Day>`,
      node("Name", day, 6),
      `      <Long_Name></Long_Name>`,
      `    </Real_Day>`
    ].join("\n")),
    `  </Real_Days_List>`
  ].join("\n");
}

function buildHoursXml(hours: string[]): string {
  return [
    `  <Hours_List>`,
    `    <Number_of_Hours>${hours.length}</Number_of_Hours>`,
    ...hours.map((hour) => [
      `    <Hour>`,
      node("Name", hour, 6),
      `      <Long_Name></Long_Name>`,
      `    </Hour>`
    ].join("\n")),
    `  </Hours_List>`
  ].join("\n");
}

function buildRealHoursXml(hours: string[]): string {
  return [
    `  <Real_Hours_List>`,
    `    <Number_of_Real_Hours>${hours.length}</Number_of_Real_Hours>`,
    ...hours.map((hour) => [
      `    <Real_Hour>`,
      node("Name", hour, 6),
      `      <Long_Name></Long_Name>`,
      `    </Real_Hour>`
    ].join("\n")),
    `  </Real_Hours_List>`
  ].join("\n");
}

function buildSubjectsXml(subjects: string[]): string {
  return [
    `  <Subjects_List>`,
    ...subjects.map((subject) => [
      `    <Subject>`,
      node("Name", subject, 6),
      `      <Long_Name></Long_Name>`,
      `      <Code></Code>`,
      `      <Comments></Comments>`,
      `    </Subject>`
    ].join("\n")),
    `  </Subjects_List>`
  ].join("\n");
}

function buildTagsXml(tags: string[]): string {
  return [
    `  <Activity_Tags_List>`,
    ...tags.map((tag) => [
      `    <Activity_Tag>`,
      node("Name", tag, 6),
      `      <Long_Name></Long_Name>`,
      `      <Code></Code>`,
      `      <Printable>true</Printable>`,
      `      <Comments></Comments>`,
      `    </Activity_Tag>`
    ].join("\n")),
    `  </Activity_Tags_List>`
  ].join("\n");
}

function buildTeachersXml(teachers: Teacher[], useMorningAfternoonMode: boolean): string {
  return [
    `  <Teachers_List>`,
    ...teachers.map((teacher) => [
      `    <Teacher>`,
      node("Name", teacher.name, 6),
      `      <Long_Name></Long_Name>`,
      `      <Code></Code>`,
      useMorningAfternoonMode
        ? `      <Mornings_Afternoons_Behavior>${teacher.morningsAfternoonsBehavior || "Unrestricted"}</Mornings_Afternoons_Behavior>`
        : "",
      `      <Target_Number_of_Hours>${teacher.targetHours || 0}</Target_Number_of_Hours>`,
      `      <Qualified_Subjects>`,
      `      </Qualified_Subjects>`,
      `      <Comments></Comments>`,
      `    </Teacher>`
    ].filter(Boolean).join("\n")),
    `  </Teachers_List>`
  ].join("\n");
}

function buildStudentsXml(project: TimetableProject, classes: SchoolClass[]): string {
  return [
    `  <Students_List>`,
    ...classes.map((schoolClass) => {
      return [
        `    <Year>`,
        node("Name", fetClassName(project, schoolClass), 6),
        `      <Long_Name></Long_Name>`,
        `      <Code></Code>`,
        `      <Number_of_Students>${schoolClass.studentCount || 0}</Number_of_Students>`,
        `      <Comments></Comments>`,
        `      <Number_of_Categories>0</Number_of_Categories>`,
        `      <First_Category_Is_Permanent>false</First_Category_Is_Permanent>`,
        `      <Separator> </Separator>`,
        `    </Year>`
      ].join("\n");
    }),
    `  </Students_List>`
  ].join("\n");
}

function buildActivitiesXml(project: TimetableProject, activities: FetActivity[]): string {
  const forceCampusPrefix = getCampuses(project).length > 1;
  return [
    `  <Activities_List>`,
    ...activities.map((activity) => [
      `    <Activity>`,
      activity.teacherName ? node("Teacher", activity.teacherName, 6) : "",
      node("Subject", activity.subjectName, 6),
      activity.tag ? node("Activity_Tag", activity.tag, 6) : "",
      node("Students", fetClassNameFromParts(activity.campusName, activity.className, forceCampusPrefix), 6),
      `      <Duration>${activity.duration}</Duration>`,
      `      <Total_Duration>${activity.totalDuration}</Total_Duration>`,
      `      <Id>${activity.id}</Id>`,
      `      <Activity_Group_Id>${activity.groupId}</Activity_Group_Id>`,
      `      <Active>true</Active>`,
      `      <Comments></Comments>`,
      `    </Activity>`
    ].filter(Boolean).join("\n")),
    `  </Activities_List>`
  ].join("\n");
}

function getCampuses(project: TimetableProject): Campus[] {
  const explicit = project.settings.campuses || [];
  const fromClasses = project.classes.map((schoolClass) => schoolClass.campusName);
  const fromAssignments = project.assignments.map((assignment) => assignment.campusName);
  const names = uniqueNames([
    ...explicit.map((campus) => campus.name),
    ...fromClasses,
    ...fromAssignments,
    project.settings.institutionName
  ]);
  return names.map((name) => {
    const existing = explicit.find((campus) => campus.name === name);
    return existing || { id: name, name };
  });
}

function uniqueClasses(project: TimetableProject, assignments: Assignment[]): SchoolClass[] {
  const byKey = new Map<string, SchoolClass>();
  for (const schoolClass of project.classes) {
    if (!schoolClass.campusName || !schoolClass.name) continue;
    byKey.set(classKey(schoolClass.campusName, schoolClass.name), schoolClass);
  }
  for (const assignment of assignments) {
    const key = classKey(assignment.campusName, assignment.className);
    if (!byKey.has(key)) {
      byKey.set(key, {
        id: key,
        name: assignment.className,
        campusName: assignment.campusName,
        homeroomTeacherName: ""
      });
    }
  }
  return Array.from(byKey.values());
}

function fetClassName(project: TimetableProject, schoolClass: SchoolClass): string {
  return fetClassNameFromParts(schoolClass.campusName, schoolClass.name, getCampuses(project).length > 1);
}

function fetClassNameFromParts(campusName: string, className: string, forceCampusPrefix = true): string {
  return forceCampusPrefix ? `${campusName} - ${className}` : className;
}

function roomNameForClass(project: TimetableProject, schoolClass: SchoolClass): string {
  return `Phòng ${fetClassName(project, schoolClass)}`;
}

function classKey(campusName: string, className: string): string {
  return `${campusName}::${className}`;
}

function mergeTeachers(teachers: Teacher[], assignments: Assignment[]): Teacher[] {
  const byName = new Map<string, Teacher>();
  for (const teacher of teachers) {
    if (teacher.name.trim()) byName.set(teacher.name, teacher);
  }
  for (const assignment of assignments) {
    if (assignment.teacherName.trim() && !byName.has(assignment.teacherName)) {
      byName.set(assignment.teacherName, {
        id: assignment.teacherName,
        name: assignment.teacherName,
        campusNames: uniqueNames(assignments.filter((item) => item.teacherName === assignment.teacherName).map((item) => item.campusName)),
        morningsAfternoonsBehavior: "Unrestricted"
      });
    }
  }
  return Array.from(byName.values());
}

function warnCapacity(project: TimetableProject, assignments: Assignment[], sessionCapacity: number, warnings: string[]): void {
  const classTotals = sumBy(assignments, (assignment) => assignment.className, (assignment) => assignment.weeklyPeriods);
  for (const [className, total] of classTotals) {
    if (total > sessionCapacity) {
      warnings.push(`${className}: tổng ${total} tiết vượt sức chứa ${sessionCapacity} ô.`);
    }
  }

  const teacherSlots = sessionCapacity;
  const unavailableByTeacher = new Map(project.constraints.teacherUnavailableTimes.map((item) => [item.teacherName, item.slots.length]));
  const teacherTotals = sumBy(assignments.filter((item) => item.teacherName), (assignment) => assignment.teacherName, (assignment) => assignment.weeklyPeriods);
  for (const [teacherName, total] of teacherTotals) {
    const capacity = teacherSlots - (unavailableByTeacher.get(teacherName) || 0);
    if (total > capacity) {
      warnings.push(`${teacherName}: tổng ${total} tiết vượt số ô có thể dạy là ${capacity}.`);
    }
  }
}

function realDaysFullyUnavailable(project: TimetableProject, teacherName: string): string[] {
  const calendar = buildCalendar(project.settings);
  const unavailable = project.constraints.teacherUnavailableTimes.find((item) => item.teacherName === teacherName)?.slots || [];
  const busy = new Set(unavailable.map((slot) => `${slot.dayLabel}::${slot.periodIndex}`));
  const fullyBusy: string[] = [];

  for (let realDayIndex = 0; realDayIndex < project.settings.numberOfDays; realDayIndex += 1) {
    const dayLabels = project.settings.mode === "full-day"
      ? [calendar.dayNames[realDayIndex * 2], calendar.dayNames[realDayIndex * 2 + 1]].filter(Boolean)
      : [calendar.dayNames[realDayIndex]].filter(Boolean);
    const totalSlots = dayLabels.length * project.settings.periodsPerSession;
    let busySlots = 0;

    for (const dayLabel of dayLabels) {
      for (let periodIndex = 0; periodIndex < project.settings.periodsPerSession; periodIndex += 1) {
        if (busy.has(`${dayLabel}::${periodIndex}`)) busySlots += 1;
      }
    }

    if (totalSlots > 0 && busySlots === totalSlots) {
      fullyBusy.push(calendar.realDayNames[realDayIndex] || calendar.dayNames[realDayIndex] || `Ngày ${realDayIndex + 1}`);
    }
  }

  return fullyBusy;
}

function totalPeriodsByTeacher(assignments: Assignment[]): Map<string, number> {
  return sumBy(
    assignments.filter((assignment) => assignment.teacherName),
    (assignment) => assignment.teacherName,
    (assignment) => assignment.weeklyPeriods
  );
}

function sumBy<T>(items: T[], keyOf: (item: T) => string, valueOf: (item: T) => number): Map<string, number> {
  const totals = new Map<string, number>();
  for (const item of items) {
    const key = keyOf(item);
    totals.set(key, (totals.get(key) || 0) + valueOf(item));
  }
  return totals;
}

function uniqueNames(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)));
}

function node(name: string, value: string, indent: number): string {
  return `${" ".repeat(indent)}<${name}>${escapeXml(value)}</${name}>`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function weightPercent(weight: number): string {
  const normalized = Number.isFinite(weight) ? weight : 1;
  const percent = normalized <= 1 ? normalized * 100 : normalized;
  return trimFloat(Math.min(100, Math.max(0, percent)));
}

function trimFloat(value: number): string {
  return Number(value.toFixed(4)).toString();
}

function clampInteger(value: number, min: number, max: number): number {
  if (!Number.isFinite(value)) return min;
  return Math.max(min, Math.min(max, Math.trunc(value)));
}

function normalizeOptionalInteger(value: number | undefined): number | undefined {
  if (value === undefined || !Number.isFinite(value)) return undefined;
  return Math.trunc(value);
}

function isFlagCeremonySubject(subjectName: string): boolean {
  return normalizeVietnamese(subjectName) === "chao co";
}

function normalizeVietnamese(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ");
}

function hourName(project: TimetableProject, periodIndex: number): string {
  return buildCalendar(project.settings).hourNames[periodIndex] || `Tiết ${periodIndex + 1}`;
}
